### ISSUE TITLE
Fix Travis CI cache

### ISSUE THREAD

**Issue by franz-josef-kaiser** [franz-josef-kaiser/Docker-Alpine-Nodejs#5]
Type of issue: Bug report
### Expected/Desired behavior

Travis CI should use the Bundler cache to fetch Gems from there to speed up the build. This should happen automatically.
### Actual/Current behavior

Travis CI does [not yet](https://docs.travis-ci.com/user/caching/) enable cache per default. Cache therefore [fails miserably](https://travis-ci.org/franz-josef-kaiser/Docker-Alpine-Nodejs/builds/115341007#L188).
### Proposed Change

The `.travis.yml` file in theory is set up [properly](https://github.com/franz-josef-kaiser/Docker-Alpine-Nodejs/blob/b530349513c7a0590353876d003612dae7297b19/.travis.yml#L4-L5). Practically, there's no boolean value, just a list of values for enabled caches, per the Travis docs:

``` yml
language: ruby
cache:
  - bundler
```

It seems the _boolean syntax_ is only used when _disabling_ caches or when used in combination with `directories` directive:

``` yml
cache:
  bundler: true
  directories:
  - vendor/something
  - .autoconf
```

``` yml
cache:
  bundler: false
  apt: true
```

^  not sure why that should work.
